### ISSUE TITLE
GTA III/VC don't start on Insider Windows 11 24H2 (26120.2200)

### ISSUE THREAD

**Issue by iGom** [CookiePLMonster/SilentPatch#32]
Not sure if this is a 24H2 update issue but GTA 3 and VC won't launch on my system with the new SilentPatch+ddraw (old as well)
I checked it on freshly installed versions from Steam, the only way for me to run them is to use re3/reVC

Video
https://github.com/user-attachments/assets/91aec729-cc56-40bb-840a-965a251f2e3b
https://github.com/user-attachments/assets/4ffccc4c-42c9-4362-9b26-1347afe350c4

**Comment by iGom** [comment]
SA works fine

**Comment by iGom** [comment]
ok, found the issue
Force randomization for images (ASLR mandatory) under App and Browse in Windows Defender Security Center is now globally on Windows 11, disabling this for 3/VC EXEs allows games to run
![image](https://github.com/user-attachments/assets/d2cb44c0-c1ac-4bc0-8fb2-b5be7be5b8f9)

I guess it's not something that SP could fix as the problem is with the game EXEs

**Comment by CookiePLMonster** [comment]
> I guess it's not something that SP could fix as the problem is with the game EXEs

That depends, because in this SP update I actually made sure that III/VC patches can deal with ASLR if it's present. The main question is - do they work without SP? If they launch and the patch makes it crash, then it's a problem on my end that I need to fix. If they can't even boot, I'm almost 100% certain it will be unfixable - for example, last time I checked I found out that the very old steamstub version used in the Steam releases of III and VC can't handle ASLR, and I cannot do anything about that.

In fact, perhaps this is your issue? I recommend to try stripping Steamstub out of those executables with Steamless. You **should** be able to use Mandatory ASLR fine then.

**Comment by iGom** [comment]
> The main question is - do they work without SP?
Nope until Mandatory ASLR is disabled for them
> In fact, perhaps this is your issue? I recommend to try stripping Steamstub out of those executables with Steamless. You **should** be able to use Mandatory ASLR fine then.

I've never heard of SeamLess, but it did the trick, now both of games start just fine with or without SP and

**Comment by CookiePLMonster** [comment]
Nice! In this case it's something that SP cannot realistically address. If it was broken in the game code itself then I probably could fix it in the DDraw Component, like I fix the DEP issues. But, Steamstub is out of reach.

Closing as solved since it works fine with SP.
