### ISSUE TITLE
GTA VC - Cheetah has the VCPD Cheetah siren inside

### ISSUE THREAD

**Issue by sebblevy** [CookiePLMonster/SilentPatch#35]
The simple Cheetah for some reason spawned with the siren from VCPD Cheetah.. 
![12110_566](https://github.com/user-attachments/assets/61855f04-5a20-46cc-9efe-8c0117485616)

**Comment by CookiePLMonster** [comment]
![image](https://github.com/user-attachments/assets/7dd1ca77-5af1-47ae-83f4-5c725d8efcce)

Indeed, looks like the civilian Cheetah has a siren as an extra. However, two things to note:
1. SilentPatch does not fix model/asset issues, so this is out of scope.
2. I can imagine this being 100% intentional, a fake siren put there to "scare" people. The fact VCPD Cheetah has a siren always and this is an extra seems to further imply it was intentional.

Because of the combination of those two points, there's nothing for me to do here.
